# jd_processor.py
import numpy as np
from modules.shared_model import sentence_model


def embed_jd(jd_text):
    """
    Embed a job description string into a normalized float32 vector.

    Must use normalize_embeddings=True so the vector is in the same
    space as resume embeddings generated by embedding_engine.py.
    Both use FAISS IndexFlatIP (inner-product = cosine sim when normalized).
    """
    if not jd_text or not jd_text.strip():
        jd_text = "software engineer job description"

    embedding = sentence_model.encode(jd_text, normalize_embeddings=True)
    return embedding.astype(np.float32)